# Generated by Django 5.1.1 on 2024-09-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_medicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='medicine',
        ),
        migrations.AddField(
            model_name='order',
            name='item_name',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
