# Generated by Django 5.1.1 on 2024-09-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_order_medicine_order_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
