# Generated by Django 5.1.1 on 2024-09-19 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item_price',
            new_name='product_price',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
