# Generated by Django 5.1.1 on 2024-09-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_description_transaction_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='Product_name',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='price',
            new_name='Product_price',
        ),
    ]
