# Generated by Django 5.1.1 on 2024-09-20 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_order_product_name_remove_order_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine'),
        ),
    ]
